version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./gateway
    container_name: opsbuddy-gateway
    ports:
      - "8000:8000"
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8000
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - FILE_SERVICE_HOST=file-service
      - FILE_SERVICE_PORT=8001
      - UTILITY_SERVICE_HOST=utility-service
      - UTILITY_SERVICE_PORT=8002
      - ANALYTICS_SERVICE_HOST=analytics-service
      - ANALYTICS_SERVICE_PORT=8003
      - TIMESERIES_SERVICE_HOST=timeseries-service
      - TIMESERIES_SERVICE_PORT=8004
    depends_on:
      - file-service
      - utility-service
      - analytics-service
      - timeseries-service
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # File Service
  file-service:
    build: ./services/file-service
    container_name: opsbuddy-file-service
    ports:
      - "8001:8001"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8001
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=your_influxdb_token_here
      - INFLUXDB_ORG=opsbuddy
      - INFLUXDB_DATABASE=opsbuddy
      - INFLUXDB_URL=http://influxdb:8086
      - MAX_FILE_SIZE=104857600
      - UPLOAD_DIRECTORY=./uploads
      - ALLOWED_FILE_TYPES=txt,log,json,csv,yaml,yml
    volumes:
      - file_uploads:/app/uploads
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # Utility Service
  utility-service:
    build: ./services/utility-service
    container_name: opsbuddy-utility-service
    ports:
      - "8002:8002"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8002
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=your_influxdb_token_here
      - INFLUXDB_ORG=opsbuddy
      - INFLUXDB_DATABASE=opsbuddy
      - INFLUXDB_URL=http://influxdb:8086
      - COMMAND_TIMEOUT=30
      - MAX_COMMAND_OUTPUT=1048576
      - ALLOWED_COMMANDS=ls,ps,df,free,uptime
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # Analytics Service
  analytics-service:
    build: ./services/analytics-service
    container_name: opsbuddy-analytics-service
    ports:
      - "8003:8003"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8003
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=your_influxdb_token_here
      - INFLUXDB_ORG=opsbuddy
      - INFLUXDB_DATABASE=opsbuddy
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # Timeseries DB Service
  timeseries-service:
    build: ./services/timeseries-service
    container_name: opsbuddy-timeseries-service
    ports:
      - "8004:8004"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8004
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=your_influxdb_token_here
      - INFLUXDB_ORG=opsbuddy
      - INFLUXDB_DATABASE=opsbuddy
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # InfluxDB 2.x
  influxdb:
    image: influxdb:2.7
    container_name: opsbuddy-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=opsbuddy
      - DOCKER_INFLUXDB_INIT_BUCKET=opsbuddy
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_influxdb_token_here
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped
    networks:
      - opsbuddy-network

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: opsbuddy-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - opsbuddy-network

volumes:
  influxdb_data:
  influxdb_config:
  file_uploads:
  # redis_data:

networks:
  opsbuddy-network:
    driver: bridge
